const types = {
  GET_SELECTED_POST_REQUEST: "GET_SELECTED_POST_REQUEST",
  GET_SELECTED_POST_SUCCESS: "GET_SELECTED_POST_SUCCESS",
  GET_SELECTED_POST_ERROR: "GET_SELECTED_POST_ERROR",
  POST_COMMENT_BY_ID_SUCCESS: "POST_COMMENT_BY_ID_SUCCESS"
};

export default types;
