const types = {
  GET_SELECTED_POST_REQUEST: "GET_SELECTED_POST_REQUEST",
  GET_SELECTED_POST_SUCCESS: "GET_SELECTED_POST_SUCCESS",
  GET_SELECTED_POST_ERROR: "GET_SELECTED_POST_ERROR",
};

export default types;
