export const headerTitle = 'Test Task';
export const shortArticleLength = 150; // size of closed article
export const readFull = 'read full';
export const deletePostText = 'delete post';
export const successDeletePost = 'Post has been deleted';
export const successVariant = 'success';
export const errorVariant = 'Error';
export const errorFetchText = 'Error fetching data!';
export const maxWidth = 'sm';
export const successFetchPosts = 'Posts successfully received';
