export const headerTitle = 'Test Task';
export const postsList = 'Posts List:';
export const shortArticleLength = 150; //size of closed article
export const readFull = 'read full';
export const deletePostText = 'delete post';
export const successDeletePost = 'Post has been deleted';
export const successVariant = 'success';
export const errorVariant = 'error';
export const maxWidth = 'sm';
export const successFetchPosts = 'Posts successfully received';
export const successFetchPost = 'Post successfully received';
