const types = {
  GET_ALL_POSTS_REQUEST: 'GET_ALL_POSTS_REQUEST',
  GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
  GET_ALL_POSTS_ERROR: 'GET_ALL_POSTS_ERROR',
  DELETE_SELECTED_POST_SUCCESS: 'DELETE_SELECTED_POST_SUCCESS',
  GET_SELECTED_POST_REQUEST: 'GET_SELECTED_POST_REQUEST',
  GET_SELECTED_POST_SUCCESS: 'GET_SELECTED_POST_SUCCESS',
  GET_SELECTED_POST_ERROR: 'GET_SELECTED_POST_ERROR',
};

export default types;
